### ISSUE TITLE
Allow access to multi-tenant mongo server

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-mongodb#13]
While testing https://github.com/Microsoft/vscode/issues/25332

When you run your database on mlab you get a multi-tenant setup. I.e. a single mongo server has multiple databases but you are only allowed to access the db you own.

The mongoshell handles that case without issues:
` mongo mongodb://<dbuser>:<dbpassword>@<server>.mlab.com:55574/<database>` works without issues.

When I try to use such a connection string the in extension I get an error since the extension tries to list the databases:

`not authorized on admin to execute command { listDatabases: 1 }: MongoError: not authorized on admin to execute command { listDatabases: 1 }`

**Comment by mogarick** [comment]
Hi,

I've downloaded the extension and tried to connect to a mlab DB and got the same error.

Any hint about when is this gonna be fixed?

**Comment by abhritchie** [comment]
Hi,
I get the exact same error connecting to a locally-hosted, multi-tenant database.
Thanks in advance!

**Comment by DonkeyTronKilla** [comment]
Same issue connecting to mlab db

**Comment by maxisam** [comment]
Any progress on this?

**Comment by chrisdias** [comment]
This extension is not being actively developed anymore, all of our efforts have moved to the cosmosdb extension: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb
