### ISSUE TITLE
cannot do find() projection

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-mongodb#20]
Try running this from a mongo document (any collection, does not matter if its stickers):

```
db.stickers.find({}, {"_id":0})
```

The result will still contain the `_id` field.

Run the same query from the Mongo shell and the `_id` field is not in the result set.

It is not just the `_id` field, you can't do any projection such as:

```
db.stickers.find({}, {"name":1, "_id":0})
```

**Comment by StephenWeatherford** [comment]
If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  

Projections are now supported with the newest release, so please give it a try and let us know if you have any problems.

Thanks!
Stephen
