### ISSUE TITLE
tree not being refreshed on windows

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-mongodb#27]
running on windows 10...

add a new connection
result: the Mongo tree is not updated to see the connection
press refresh button
result: same, no connection in the tree
reload/restart VS Code
result: now i can see the connection and work with it
drop a database
result: database is still in the tree
reload/restart VS Code
result: now the database is removed from the tree

i dont see this on Mac, only windows

**Comment by sandy081** [comment]
@chrisdias This is due to https://github.com/Microsoft/vscode/issues/31191
