### ISSUE TITLE
cannot format result.json

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-mongodb#3]
right click on `result.json`:

![image](https://cloud.githubusercontent.com/assets/1487073/24383124/fbb0d2d4-130f-11e7-8c95-1ef455c351c0.png)

**Comment by EricJizbaMSFT** [comment]
This has been fixed already, I believe originally in this commit: https://github.com/Microsoft/vscode-mongodb/commit/ae2b7f3be797fffb68399ff9d9b26faa6929112d
