### ISSUE TITLE
Using db.<collection>.find to find based on _id and ObjectId

### ISSUE THREAD

**Issue by supersime** [Microsoft/vscode-mongodb#44]
I'm on Windows version of VS Code version 1.18.1, have mongo v3.4.4.

In a Scrapbook, I have this command:
`db.<collection>.find({"_id": ObjectId("5a12639c9e07f595e0c79c89")})`

and I get this error:

> ObjectId is not defined

Have also tried with ObjectID.

Am sure this will be a basic issue. Any ideas?

**Comment by StephenWeatherford** [comment]
@supersime If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  

That said, this functionality is not currently supported in either extension. If you would like us to consider fixing this in the newer extension, please enter an issue here: https://github.com/Microsoft/vscode-cosmosdb/issues

thx,
Stephen
