### ISSUE TITLE
the command can only run one the first line in "Scrapbook"

### ISSUE THREAD

**Issue by chenjunup** [Microsoft/vscode-mongodb#48]
when i try to write command in the "Scrapbook" and to run it, and i find out that it can only work when i run selected command on the first line.And also the IntelliSense works for the only first line.
I wonder it's my owm problem or it's the way works.

**Comment by StephenWeatherford** [comment]
@chenjunup Please switch to using this extension: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb
We just fixed several issues with the scrapbook (including this one) and also will be shipping further improvements in a few weeks.  Thanks.
