### ISSUE TITLE
Execute script: run the current line if nothing is selected

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-mongodb#5]
Testing https://github.com/Microsoft/vscode/issues/25332

I had a hard time to figure out how 'Execute script' works. I always put the cursor after an expression and expected it to be evaluated.

IMO if the current selection is empty, I suggest to run the line on which the cursor is.

**Comment by EricJizbaMSFT** [comment]
This has been fixed already, I believe originally in this commit:

https://github.com/Microsoft/vscode-mongodb/commit/d559f427ffc27873ecddffd943f58e69d3afb22b#diff-642d30b32e9e553bf3e4cb781356c62bR71
