### ISSUE TITLE
Code completions: Sort collections before functions

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-mongodb#8]
Testing https://github.com/Microsoft/vscode/issues/25332

- create a db connection
- open the test db and run some commands
- type `db.`
- it would be nice to see the collections first

![image](https://cloud.githubusercontent.com/assets/6461412/25435793/8d5c0d96-2a91-11e7-8285-351823247243.png)

**Comment by EricJizbaMSFT** [comment]
Tested in latest version - this is fixed
